### ISSUE TITLE
DCR hands out a public client but Dex requires a client secret — the refresh grant cannot authenticate

### ISSUE THREAD

**Issue by jakobkolb** [jakobkolb/mcp-oauth-gateway#7]
## Summary

The Dynamic Client Registration endpoint tells clients that `claude-mcp` is a **public** client (`token_endpoint_auth_method: "none"`, no `client_secret` returned), while Dex has it configured as a **confidential** client that requires a secret on every token-endpoint call. Any client that trusts the registration response therefore gets `invalid_client` at `/token` — including on the `refresh_token` grant.

This blocks #6: even once a refresh token is issued, a DCR-registered client cannot redeem it.

## Root cause

Three sources of truth disagree about how `claude-mcp` authenticates:

| Source | Says |
|---|---|
| [`templates/well-known.yaml:38`](templates/well-known.yaml#L38) (`/register`) | `"token_endpoint_auth_method":"none"`, no `client_secret` in the response |
| [`templates/well-known.yaml:28`](templates/well-known.yaml#L28) (AS metadata) | `"token_endpoint_auth_methods_supported":["client_secret_post","client_secret_basic"]` — `"none"` is not offered |
| [`values.yaml:50-56`](values.yaml#L50-L56) (Dex static client) | `secretEnv: DEX_CLIENT_SECRET`, no `public: true` → confidential |

Dex's token endpoint enforces the secret unconditionally — `dexidp/dex` v2.41.1 `server/handlers.go` `withClientFromStorage` (~L785-828):

```go
if subtle.ConstantTimeCompare([]byte(client.Secret), []byte(clientSecret)) != 1 {
    if clientSecret == "" {
        s.logger.InfoContext(r.Context(), "missing client_secret on token request", "client_id", client.ID)
    }
    s.tokenErrHelper(w, errInvalidClient, "Invalid client credentials.", http.StatusUnauthorized)
    return
}
```

There is no `public` bypass in this code path — public clients work only because they carry an *empty* `client.Secret`, so the constant-time compare succeeds against the empty secret the client sends. With `secretEnv: DEX_CLIENT_SECRET` set, `client.Secret` is non-empty and a PKCE-only client is rejected.

The comment at [`well-known.yaml:23`](templates/well-known.yaml#L23) ("`token_endpoint_auth_methods_supported=["none"]` tells clients not to send a client_secret") documents an intent the adjacent JSON at L28 does not implement.

**Corroborating evidence:** `jakobkolb/knowledge-base` `README.md:163` instructs the operator to type the client secret into claude.ai by hand — "Advanced → OAuth Client ID: `claude-mcp`, OAuth Client Secret: `<dexClientSecret>`". That manual step exists precisely because the registration DCR returns does not work on its own. Clients that have no such manual field (Claude Code, Claude Desktop) are left with a public-client registration that Dex will not accept.

## Proposed fix

**Option A (preferred) — make `claude-mcp` a genuine public client.** PKCE (S256) is already advertised and is the auth method the MCP spec expects for this flow.

1. In `values.yaml`, drop the secret from the static client:
   ```yaml
   staticClients:
     - id: claude-mcp
       name: Claude MCP
       public: true          # replaces secretEnv: DEX_CLIENT_SECRET
       redirectURIs:
         - https://claude.ai/api/mcp/auth_callback
   ```
2. In `well-known.yaml:28`, make the AS metadata match the DCR response:
   ```json
   "token_endpoint_auth_methods_supported":["none"]
   ```
3. **Check the oauth2-proxy side before merging.** oauth2-proxy runs with `skip-jwt-bearer-tokens: true`, so it validates the bearer JWT's audience against its configured `client-id`. It still requires a non-empty `client-secret` at startup even though the value is unused in bearer-only mode. Confirm that a dummy secret is accepted, or keep the confidential client for oauth2-proxy and register a second public client for MCP clients — in which case the audience changes and oauth2-proxy needs `--oidc-extra-audience=<public-client-id>`.
4. Remove the manual client-secret step from the `knowledge-base` README once this lands.

**Option B (lower effort, worse hygiene) — make DCR self-consistent as a confidential client.** Have `/register` return the real `client_secret` and `"token_endpoint_auth_method":"client_secret_post"`. This works, but `/register` is unauthenticated, so the shared secret would be handed to any caller — it stops being a secret. Only worth doing if Option A is blocked by oauth2-proxy.

## Verification

```bash
# DCR response and AS metadata must agree on the auth method
curl -s -X POST https://auth.<baseDomain>/register -d '{}' | jq .token_endpoint_auth_method
curl -s https://auth.<baseDomain>/.well-known/oauth-authorization-server | jq .token_endpoint_auth_methods_supported

# A PKCE-only code exchange (no client_secret) must succeed, not return invalid_client
curl -s -X POST https://auth.<baseDomain>/token \
  -d grant_type=authorization_code -d code=<code> \
  -d redirect_uri=https://claude.ai/api/mcp/auth_callback \
  -d code_verifier=<verifier> -d client_id=claude-mcp

# And so must the refresh grant
curl -s -X POST https://auth.<baseDomain>/token \
  -d grant_type=refresh_token -d refresh_token=<rt> -d client_id=claude-mcp
```

Also worth checking `kubectl logs deploy/<release>-dex | grep client_secret` — "missing client_secret on token request" entries are the direct fingerprint of this bug.

## Related

- #6 — no refresh token is issued at all; this issue blocks that fix from working for DCR clients.

**Comment by jakobkolb** [comment]
## Reproduced — and the open question about oauth2-proxy is resolved: **Option A works**

Same local stack as #6 (chart's rendered ConfigMap + Dex v2.41.1 + real oauth2-proxy v7.7.1).

### The mismatch, confirmed

Against the chart as it stands, with the Dex client configured confidentially (`secret:` set, mirroring `secretEnv: DEX_CLIENT_SECRET`):

```
/register  token_endpoint_auth_method              : none
/register  client_secret returned?                 : False
AS meta    token_endpoint_auth_methods_supported   : ['client_secret_post', 'client_secret_basic']
AGREE?     False
```

A client that believes the registration it was handed cannot authenticate — on either grant:

```
T4  refresh grant as a public client (no client_secret, as /register instructs)
    HTTP 401 -> {"error": "invalid_client", "error_description": "Invalid client credentials."}
T5  same refresh grant WITH the client_secret
    HTTP 200 -> ['access_token','expires_in','id_token','refresh_token','token_type']
T6  authorization-code exchange as a public client (PKCE only, no secret)
    HTTP 401 -> {"error": "invalid_client", "error_description": "Invalid client credentials."}
```

And the predicted fingerprint appears verbatim in the Dex log:

```
level=INFO msg="missing client_secret on token request" client_id=claude-mcp
```

This is worth stressing: it is not only the refresh grant that breaks. **The initial code exchange fails too** for any client that has no manual client-secret field — which is exactly why `knowledge-base` `README.md:163` tells the operator to paste the secret into claude.ai's Advanced settings, and exactly why Claude Code / Claude Desktop cannot connect through pure DCR + PKCE.

### Option A verified — no second client, no `--oidc-extra-audience` needed

I flagged as a blocker that oauth2-proxy might refuse to start, or fail bearer validation, once `claude-mcp` becomes public. Tested directly:

- Dex static client changed to `public: true` with `secretEnv` removed.
- oauth2-proxy started with `--client-id=claude-mcp --client-secret=unused-dummy` and the chart's other args (`--provider=oidc --skip-jwt-bearer-tokens=true --upstream=file:///dev/null --email-domain=*`).

Result: oauth2-proxy **starts cleanly** and bearer validation is unaffected — a valid Dex `id_token` still passes the ingress auth subrequest and reaches the upstream (`HTTP 200`), while no-token and malformed-token requests are still rejected with 401. In `--skip-jwt-bearer-tokens` mode the secret is only used for the interactive login flow that never runs here, so a placeholder is sufficient. The audience stays `claude-mcp`, so nothing about oauth2-proxy's audience check changes.

Full regression after the change: **10/10**, including `T4 PKCE-only code exchange (no secret)`, `T6 refresh grant works with NO client_secret`, `T6b rotated refresh_token returned`, and `T8 valid token still reaches upstream (oauth2-proxy OK with dummy secret)`.

### Resulting fix

```diff
--- a/values.yaml
+++ b/values.yaml
     staticClients:
       - id: claude-mcp
         name: Claude MCP
-        secretEnv: DEX_CLIENT_SECRET
+        public: true
         redirectURIs:
           - https://claude.ai/api/mcp/auth_callback
```

```diff
--- a/templates/well-known.yaml
+++ b/templates/well-known.yaml
-..."token_endpoint_auth_methods_supported":["client_secret_post","client_secret_basic"]...
+..."token_endpoint_auth_methods_supported":["none"]...
```

`/register` already returns `"token_endpoint_auth_method":"none"` and needs no change — after this the three sources of truth finally agree, and the comment at `well-known.yaml:23` becomes accurate.

**Option B (returning the real secret from `/register`) should now be dropped** — Option A is confirmed working, and B would hand the shared secret to any unauthenticated caller.

Follow-ups once this lands: remove the manual client-secret step from `knowledge-base` `README.md:163` (tracked in jakobkolb/knowledge-base#16), and note that `DEX_CLIENT_SECRET` is still needed by the `oauth2-proxy` Secret even though Dex no longer uses it — or replace it there with an explicit placeholder so its role is not misread.

---
_Generated by [Claude Code](https://claude.ai/code)_
